name: Metrics embed
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:   
          filename: metrics.classic.svg
          token: ${{ secrets.Metrics_Stats }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
